### ISSUE TITLE
Naxxramas 10/25 - Portal to Sapphiron's Lair  / Kel'Thuzad's Chamber not working

### ISSUE THREAD

**Issue by nfernix** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#42]
I cannot 100% confirm that the portal to Sapphiron's Lair is not working on 25 man as my guild has only had this issue on 10 man, although other reports on the server were saying it was a bug in 25 man too.

We cleared all bosses up to Sapphiron on 10 man and tried to enter the portal, but it did not work. 

Some people were saying resetting the instance, reforming the group and completely leaving the instance and rezoning in would work, but did not for us.

**Comment by Zerixx** [comment]
Fixed 02/02/17

**Comment by nfernix** [comment]
So I went into our Naxx 10 raid instance ID (16) and the portal to Sapphiron is still not working. Is there anyway you could get it working for us specifically? Character in-game is Rylie. The leader of the party for the ID is Squishy

**Comment by Zerixx** [comment]
We talked ingame. I'm still working on your thing :)
